name: Continuous Delivery (snapshot)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
    
  publish:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
    - uses: actions/checkout@v4
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: debug
      run: ls -al /home/runner/.gnupg

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: zulu

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6

    - name: Publish to the Maven Central Repository
      env:
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      run: |
          ./gradlew -Ptarget=snapshot \
            clean publishToSonatype
